parameters:

    #
    # Factory
    #
    elcodi.factory.newsletter_subscription.class: Elcodi\Component\Newsletter\Factory\NewsletterSubscriptionFactory

    #
    # Services
    #
    elcodi.manager.newsletter.class: Elcodi\Component\Newsletter\Services\NewsletterManager

    #
    # Event Listeners
    #
    elcodi.event_listener.newsletter.class: Elcodi\Component\Newsletter\EventListener\NewsletterEventListener

    #
    # Event Dispatchers
    #
    elcodi.event_dispatcher.newsletter.class: Elcodi\Component\Newsletter\EventDispatcher\NewsletterEventDispatcher
