parameters:

    #
    # Entities
    #
    elcodi.core.newsletter.entity.newsletter_subscription.class: Elcodi\NewsletterBundle\Entity\NewsletterSubscription

    #
    # Repositories
    #
    elcodi.core.newsletter.repository.newsletter_subscription.class: Elcodi\NewsletterBundle\Repository\NewsletterSubscriptionRepository

    #
    # Factory
    #
    elcodi.core.newsletter.factory.newsletter_subscription.class: Elcodi\NewsletterBundle\Factory\NewsletterSubscriptionFactory

    #
    # Services
    #
    elcodi.core.newsletter.service.newsletter_manager.class: Elcodi\NewsletterBundle\Services\NewsletterManager

    #
    # Event Listeners
    #
    elcodi.core.newsletter.event_listener.newsletter.class: Elcodi\NewsletterBundle\EventListener\NewsletterEventListener

    #
    # Event Dispatchers
    #
    elcodi.core.newsletter.event_dispatcher.newsletter.class: Elcodi\NewsletterBundle\EventDispatcher\NewsletterEventDispatcher
