services:

    #
    # Event Dispatchers
    #
    elcodi.event_dispatcher.newsletter:
        class: %elcodi.event_dispatcher.newsletter.class%
        parent: elcodi.core.core.event_dispatcher.abstract
