services:

    #
    # Event Listeners
    #
    elcodi.event_listener.newsletter:
        class: %elcodi.event_listener.newsletter.class%
        arguments:
            newsletter_object_manager: @elcodi.object_manager.newsletter_subscription
        tags:
            - { name: kernel.event_listener, event: newsletter.onsubscribe, method: onNewsletterSubscribeFlush, priority: 0 }
            - { name: kernel.event_listener, event: newsletter.onunsubscribe, method: onNewsletterUnsubscribeFlush, priority: 0 }
