services:

    #
    # Object Managers
    #
    elcodi.object_manager.newsletter_subscription:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.newsletter.entity.newsletter_subscription.class% ]
