services:

    #
    # Repositories
    #

    #
    # Repository for entity newsletter_subscription
    #
    elcodi.repository.newsletter_subscription:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.newsletter.entity.newsletter_subscription.class%
