services:

    #
    # Repositories
    #

    #
    # Repository for entity newsletter_subscription
    #
    elcodi.repository.newsletter_subscription:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.newsletter.entity.newsletter_subscription.class% ]
