services:

    #
    # Services
    #
    elcodi.manager.newsletter:
        class: %elcodi.manager.newsletter.class%
        arguments:
            - @elcodi.event_dispatcher.newsletter
            - @validator
            - @elcodi.factory.newsletter_subscription
            - @elcodi.repository.newsletter_subscription
            - @elcodi.generator.sha1
